### PR TITLE
Focus first form field on signup page

### PR DESCRIPTION
**Pull request by mwharrison**
From https://trello.com/c/GnqWNehB/2-bug-account-accessibility-issues
I just wanted to get Accounts up and running and do one PR. :) Feel free to tell me this isn't the correct way to do this.

### CODE REVIEW

**Comment by jpslav** [comment]
Thanks @mwharrison!  Can you add to the happy path scenarios in the log in and sign up feature specs that the intended field gets the focus?  e.g. around here https://github.com/openstax/accounts/blob/master/spec/features/user_signs_up_spec.rb#L20 for sign up and probably similar for log in.  Might need something like https://stackoverflow.com/a/13177528 but with the `expect` syntax, e.g. `expect(page.evaluate_script("document.activeElement.id")).to eq "some_id"`

**Comment by jpslav** [comment]
If you wanted to be fancy, you could even add a helper method for this ugly looking test to the `spec/feature_helpers.rb` file:

```ruby
def expect_focus_on_id(id)
  expect(page.evaluate_script("document.activeElement.id")).to eq id
end
```

**Comment by mwharrison** [comment]
@jpslav - thanks for pointing me in the right place, I wasn't finding what was failing. :)

**Comment by jpslav** [comment]
@mwharrison the failures are actually unrelated -- looks like we have some failures on master.

**Comment by mwharrison** [comment]
[Bug: Account accessibility issues](https://trello.com/c/GnqWNehB/438-bug-account-accessibility-issues)

**Pull request merged**
