### PR TITLE
Fix: Faculty Lead missing for users who sign up with social and/or as a student, then request faculty access

### PR DESCRIPTION
**Pull request by BryanEliDimas**
### The fix is to upsert salesforce leads instead of trying to update one when we don't have a lead id for them stored.

The changes in this PR are the same changes introduced in PR Upsert salesforce leads #894. I made a mistake when merging that PR (I merged it on branch v7.0.3 because it was intended to be a patch to that version) instead of master. So this PR is just to add the changes to master.

### CODE REVIEW

**Comment by BryanEliDimas** [comment]
I just need to get Travis to pass but otherwise, this PR is ready for code review.

**Review by mwharrison — APPROVED** [review]
That's a lot of test updating compared to the code changes! 😄

**Comment by BryanEliDimas** [comment]
Exactly 😅

**Comment by BryanEliDimas** [comment]
Just rebased because there was a conflict in a file. Select4d the changes from master and force-pushed.

**Pull request merged**
