### PR TITLE
Add suffix field to users

### PR DESCRIPTION
**Pull request by karenc**
I have a few questions about this change:

- I've included it in the registration form.  Should I remove it?
- I've included the suffix in users' full name.  Is it ok?

### CODE REVIEW

**Comment by Dantemss** [comment]
- That is probably fine. Is the title there too? Maybe one day the registration page and profile page could be the same...
- Full name is weird. Have to ask JP
- My preference would be to shorten the first/last name fields and leave the button on the same line, but it's up to JP.

**Comment by karenc** [comment]
@Dantemss No, I've only added suffix to the registration form.  I'll add title too.

**Comment by karenc** [comment]
I've added title to the registration form.  I've also shortened the first name and last name field on the profile form so now it looks like this:

profile

I checked that the first name and last name fields are still about 20 characters wide on my browser.  So may be it's ok?

**Comment by Dantemss** [comment]
I like it, but JP should weigh in.

**Comment by jpslav** [comment]
Looks good.  Suffix in full name fine too.

**Comment by jpslav** [comment]
Reviewed code too.  Looks good.

**Pull request merged**
