### PR TITLE
update past adopter to be using_openstax for renewal popup

### PR DESCRIPTION
**Pull request by mwvolo**
The renewal popup (the only thing I am aware of looking at this field) is showing folks the popup if their adoption status is `true`. We want the renewal popup to show for these folks, so updating this to reflect that.

### CODE REVIEW

**Comment by mwvolo** [comment]
Specs were failing, so I set the version of Chromedriver to highest available version from here: https://chromedriver.storage.googleapis.com/index.html

**Review by Dantemss — COMMENTED** [review]
Are you sure marketing doesn't use this to send emails? Also I have a fix for chromedriver on my app roles PR

**Comment by mwvolo** [comment]
Marketing does not use this specific field in the API, no.
This field is controlled in a Salesforce flow, based on if someone has a current adoption with us. 
It is then updated here to be a boolean based on what is in Salesforce (it doesn't flow from accounts to any marketing platform). 
https://github.com/openstax/accounts/blob/main/app/routines/update_user_contact_info.rb#L102

**Comment by mwvolo** [comment]
weird, I see you just updated the webdrivers gem... I couldn't seem to get that working locally but this can wait until your other PR is merged and I'll rebase

**Pull request merged**
