### PR TITLE
Add react rails

### PR DESCRIPTION
**Pull request by RoyEJohnson**
Lays the foundation for updating faculty verification forms to use React.

### CODE REVIEW

**Comment by RoyEJohnson** [comment]
[OSW2.adoptforms.07 Faculty verification form](https://trello.com/c/IeFZrjhv/671-osw2adoptforms07-faculty-verification-form)

**Comment by jpslav** [comment]
Hey @RoyEJohnson - can I join the discussion on whether we want to reactify Accounts at this particular time?  There may be reasons not to.  In any event, need to not commit the `node_modules` directory, that should be added to `.gitignore`.

**Comment by jpslav** [comment]
@RoyEJohnson I'm not a git expert, but I think you need to rebase instead of pushing a new commit, because the 5k files would still be in the history.  I could be seeing what you did incorrectly tho.

**Comment by RoyEJohnson** [comment]
[OSW2.adoptforms.07 Faculty verification form](https://trello.com/c/680rlNjl/528-osw2adoptforms07-faculty-verification-form)

**Pull request closed without merging**
