### PR TITLE
Verified email on test users

### PR DESCRIPTION
**Pull request by mwharrison**

### CODE REVIEW

**Comment by Dantemss** [comment]
Changes look good, but Travis needs some fixing.

**Comment by reedstrm** [comment]
Grr, I need this, and went to fix the tests, but ruby 2.3.7 requires an old, insecure version of libssl, which is a pain to install on ubuntu. How close are we to getting the rails5 port merged?

**Comment by mwharrison** [comment]
@Dantemss @reedstrm - I was out sick yesterday but I plan on getting these tests fixed up today!
Thanks for the review, Dante - and the attempt, Ross! 😄

**Comment by mwharrison** [comment]
@Dantemss - can you verify the updates to the tests look good?

**Pull request merged**
