### PR TITLE
removed redundant 'Please log in.' notices

### PR DESCRIPTION
**Pull request by jpslav**
The 'Please log in.' notice messages appeared right above messages like "Sign in with your one OpenStax account".  This PR removes the redundant notice.

@Dantemss can you review.  Don't merge yet.

### CODE REVIEW

**Comment by jpslav** [comment]
Used to always look like this:

image

This PR removes the blue notice.

**Comment by jpslav** [comment]
@fredasaurus / @jason-holmes can you bless this?

**Comment by jason-holmes** [comment]
Probably, but can I get a link first to see it?

-------
Jason Holmes, Ph.D.
User Experience Manager
OpenStax | OpenStax.org
(713) 893-1326

**Comment by jpslav** [comment]
Look at the screenshot and cover the “please log in” blue box with your finger ;-)

**Comment by jason-holmes** [comment]
-Stamp-  UX approved  -Stamp-

**Comment by Dantemss** [comment]
Travis failed?

**Comment by Dantemss** [comment]
But the changes seem reasonable.

**Pull request merged**
