### PR TITLE
switch from coveralls to codecov

### PR DESCRIPTION
**Pull request by philschatz**
As part of https://github.com/openstax/napkin-notes/issues/68 this switches from coveralls to codecov.

I was not sure about a couple things but took some defaults:

- [x] When should coveralls make comments on the PR and what should be included
- [x] I used this recommendation from codecov.io: https://github.com/codecov/example-ruby

### CODE REVIEW

**Comment by jpslav** [comment]
@philschatz I'd rather not have codecov comment on PRs.  I found them too loquacious with coveralls and not all that helpful.   

And I have no recollection of what simplecov does, @Dantemss do you know?

**Comment by Dantemss** [comment]
@jpslav Simplecov reports code coverage, either to a service like coveralls or codecov or as an HTML page that is stored in the `coverage` folder (but this PR disables the HTML page part)

**Comment by Dantemss** [comment]
You could probably disable the comment in codecov somewhere...

**Comment by philschatz** [comment]
hehe, configuring comments is the very 1st file in the PR diff: `.codecov.yml` 😄

**Pull request merged**
