### PR TITLE
Support multiple accounts per authentication provider

### PR DESCRIPTION
**Pull request by nathanstitt**
This allows a person to login using multiple accounts from
the same provider, as when a person has multiple gmail
accounts and wants to associate them all with a single
openstax one.

In response to issue #119

### CODE REVIEW

**Comment by jpslav** [comment]
Also, we need to address the UI to make this change apparent to users.  As it is now, once a user registers with a Google account, the button to login with Google disappears (as before we couldn't handle more than one Google authentication).  It disappearing was kind of nice because it helped drive our registering user to eventually say "finish setting up my account".  I kind of worry if we show a "sign in with Google button" after they just signed in with Google that they may get confused.  We can chat about this if not clear.

**Comment by Dantemss** [comment]
OK so the validation needs to be gone from the model...
And we need some tests to make sure that the behavior is correct (i.e. that we can add 2 authentications to a user and loging in as either one will allow you to login).

**Comment by Dantemss** [comment]
And from what JP said we need to not hide the "sign in with google" button after you sign in with google etc. And might need some UX design there.

**Comment by nathanstitt** [comment]
@Dantemss & @jpslav  I'm confused on where you see the uniqueness on the model.  Are you referring to [Authentication's uid](https://github.com/openstax/accounts/blob/master/app/models/authentication.rb#L6) validation?

If so that only checks that the UID that's returned from google/twitter/fb etc is unique.  In the case of a person having two gmail accounts, they'll have two different UIDs, but the same provider ID.

I've added some specs to `spec/models/authentication_spec.rb` that (hopefully) illustrates it.

I'm afraid I'll need a hint on removing the "sign in with google button"  I found https://github.com/openstax/accounts/blob/master/app/views/identities/new.html.erb but don't see anywhere that buttons are hidden.  Am I looking at the wrong place or is there some JS/CSS combo that hides it?

**Comment by Dantemss** [comment]
Nathan is right JP, that validation is unrelated to this issue.
Not sure about the button hiding, but I did see it being hidden in the Accounts demo during the meeting.

**Comment by jpslav** [comment]
At first I agreed with y'all that I was wrong, but I was mistaken ;-)

@nathanstitt correctly points out that the authentication UID uniqueness validation in the model is ok.  I agree with that.  But that means we should leave the uniqueness constraint in the migration (what's good for the model is even better for the DB).  

So I'm pretty sure that means these aren't the changes we were looking for.  Maybe since there aren't existing validations that require a provider to be unique for each User, that means there aren't business logic changes to be made.  

But there are at least view changes to be made (the disappearing Google login, etc).  I'll try to comment on places where we need changes.  

Does this all make sense?

**Comment by nathanstitt** [comment]
It makes 1/2 sense ;-)  I think the confusion is stemming from the problem that the constraint in the DB didn't match the AR validation.

The DB constraint that I removed was enforcing uniqueness between the `user_id` and `provider` fields, while the AR validation is enforcing uniqueness between the `uid` and `provider` fields. 

The `uid` field is populated by the oauth provider and represents a unique id for the user in their system.  The `user_id` is the ID of our user object.

If order to allow a user to have two different Google logins, they'll have the same provider listed multiple times, but each should have a unique `uid`.

Your point about the DB matching the business logic validations is good.  We should add a unique constraint in the DB to match the AR validation (on `uid` <-> `provider`).

I just found where the buttons are hidden in the view layer: [views/sessions/_login.html.erb](https://github.com/openstax/accounts/blob/master/app/views/sessions/_login.html.erb#L1-L18).  I'll get that corrected in a bit

**Comment by nathanstitt** [comment]
I've just committed the first pass at reworking the UI to support multiple logins with same provider.  I'm not at all happy with what I've came up with, but am hopeful that this is enough for us to understand the problem and brainstorm solutions around.

This is what I've came up with:
screen shot 2015-03-12 at 4 27 00 pm

I'm overlaying the plus onto the icon and changing the mouse-over (title) to reflect that the service has been used before and clicking it will add an additional account. [css](https://github.com/openstax/accounts/blob/multiple-auth-from-provider/app/assets/stylesheets/sessions.css.scss#L23-L35)  I'm unhappy with this because I really doubt that anyone's going to know what the "+" sign indicates and will probably not read the tooltip.

I think a better implementation would be to remove the icon if they've already used it and replace with either a different icon or just text reading **Add additional Twitter Login** 

However there's also space at the left that we could use to provide a grid layout that would allow us to space to write a longer description of what's going on.   People usually don't read longer descriptions though.

Any other thoughts?

**Comment by edwoodward** [comment]
Closing this due to age. It can be revisited if necessary.

**Pull request closed without merging**
